name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Publish docs
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install
        run: yarn

      - name: Build Docs
        run: yarn build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ghpages # The branch the action should deploy to.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          FOLDER: build # The folder that we serve our files from
